Ms::Score Class Reference
Libmscore Home · All Classes · All Functions · All Variables
Ms::Score Class Reference
Inherits QObject, and Ms::ScoreElement.
Inherited by Ms::MasterScore.
Public Types
enum FileError : char { FILE_NO_ERROR, FILE_ERROR, FILE_NOT_FOUND, FILE_OPEN_ERROR, FILE_BAD_FORMAT, FILE_UNKNOWN_TYPE, FILE_NO_ROOTFILE, FILE_TOO_OLD, FILE_TOO_NEW, FILE_OLD_300_FORMAT, FILE_CORRUPTED, FILE_USER_ABORT, FILE_IGNORE_ERROR }
Public Functions
Score (const Score &)=delete
Score (MasterScore *, bool forcePartStyle=true)
Score (MasterScore *, const MStyle &)
QString accessibleInfo () const
virtual std::list< MidiInputEvent > * activeMidiPitches ()
bool addArticulation (Element *, Articulation *atr)
void addArticulation (SymId)
Chord * addChord (const Fraction &tick, TDuration d, Chord *oc, bool genTie, Tuplet *tuplet)
ChordRest * addClone (ChordRest *cr, const Fraction &tick, const TDuration &d)
void addElement (Element *)
FiguredBass * addFiguredBass ()
Hairpin * addHairpin (HairpinType, ChordRest *cr1, ChordRest *cr2=nullptr, bool toCr2End=true)
Hairpin * addHairpin (HairpinType, const Fraction &tickStart, const Fraction &tickEnd, int track)
virtual void addLayoutFlags (LayoutFlags)
Lyrics * addLyrics ()
void addLyrics (const Fraction &tick, int staffIdx, const QString &)
void addMeasure (MeasureBase *, MeasureBase *)
Note * addMidiPitch (int pitch, bool addFlag)
Note * addNote (Chord *, NoteVal &noteVal, bool forceAccidental=false)
void addPitch (int pitch, bool addFlag, bool insert)
Note * addPitch (NoteVal &, bool addFlag)
void addRefresh (const QRectF &)
void addRemoveBreaks (int interval, bool lock)
Rest * addRest (const Fraction &tick, int track, TDuration, Tuplet *)
Rest * addRest (Segment *seg, int track, TDuration d, Tuplet *)
void addSpanner (Spanner *)
Note * addTiedMidiPitch (int pitch, bool addFlag, Chord *prevChord)
void addUnmanagedSpanner (Spanner *)
void addViewer (MuseScoreView *v)
void adjustBracketsDel (int sidx, int eidx)
void adjustBracketsIns (int sidx, int eidx)
void adjustKeySigs (int sidx, int eidx, KeyList km)
void appendMeasures (int)
bool appendMeasuresFromScore (Score *score, const Fraction &startTick, const Fraction &endTick)
void appendPart (const QString &)
void appendPart (Part *p)
bool appendScore (Score *, bool addPageBreak=false, bool addSectionBreak=true)
Audio * audio () const
bool autosaveDirty () const
void changeAccidental (AccidentalType)
void changeAccidental (Note *oNote, Ms::AccidentalType)
void changeCRlen (ChordRest *cr, const Fraction &, bool fillWithRest=true)
void changeCRlen (ChordRest *cr, const TDuration &)
void changeVoice (int)
bool checkClefs ()
bool checkHasMeasures () const
bool checkKeys ()
void checkSpanner (const Fraction &startTick, const Fraction &lastTick)
bool checkTimeDelete (Segment *, Segment *)
Score * clone ()
void cloneVoice (int strack, int dtrack, Segment *sf, const Fraction &lTick, bool link=true, bool spanner=true)
void cmd (const QAction *, EditData &)
void cmdAddInterval (int, const std::vector< Note * > &)
void cmdAddOttava (OttavaType)
void cmdAddPitch (int note, bool addFlag, bool insert)
void cmdAddSpanner (Spanner *spanner, const QPointF &pos, bool firstStaffOnly=false)
void cmdAddSpanner (Spanner *spanner, int staffIdx, Segment *startSegment, Segment *endSegment)
void cmdAddStretch (qreal)
void cmdAddTie (bool addToChord=false)
void cmdAddTimeSig (Measure *, int staffIdx, TimeSig *, bool local)
void cmdConcertPitchChanged (bool, bool)
void cmdCreateTuplet (ChordRest *, Tuplet *)
void cmdDecDurationDotted ()
void cmdDeleteSelection ()
void cmdDeleteTuplet (Tuplet *, bool replaceWithRest)
void cmdDoubleDuration ()
void cmdEnterRest (const TDuration &d)
void cmdExchangeVoice (int, int)
void cmdExplode ()
void cmdFullMeasureRest ()
void cmdHalfDuration ()
void cmdImplode ()
void cmdIncDurationDotted ()
void cmdInsertClef (Clef *clef, ChordRest *cr)
void cmdJoinMeasure (Measure *, Measure *)
void cmdMirrorNoteHead ()
void cmdPaste (const QMimeData *ms, MuseScoreView *view, Fraction scale=Fraction(1, 1))
void cmdRealizeChordSymbols (bool lit=true, Voicing v=Voicing(-1), HDuration durationType=HDuration(-1))
void cmdRelayout ()
void cmdRemoveEmptyTrailingMeasures ()
void cmdRemovePart (Part *)
void cmdRemoveStaff (int staffIdx)
void cmdRemoveTimeSig (TimeSig *)
void cmdResequenceRehearsalMarks ()
void cmdResetAllPositions ()
void cmdResetNoteAndRestGroupings ()
void cmdSelectAll ()
void cmdSelectSection ()
void cmdSlashFill ()
void cmdSlashRhythm ()
void cmdSplitMeasure (ChordRest *)
virtual CmdState & cmdState ()
virtual const CmdState & cmdState () const
void cmdTimeDelete ()
void cmdToggleAutoplace (bool all)
void cmdToggleLayoutBreak (LayoutBreak::Type)
void cmdToggleTie ()
System * collectSystem (LayoutContext &)
void colorItem (Element *)
void connectTies (bool silent=false)
void createBeams (Measure *)
void createCRSequence (const Fraction &f, ChordRest *cr, const Fraction &tick)
bool created () const
void createPlayEvents (Measure *start=nullptr, Measure *end=nullptr)
QString createRehearsalMarkText (RehearsalMark *current) const
void createRevision ()
QImage createThumbnail ()
Measure * crMeasure (int idx) const
int currentLayer () const
uint currentLayerMask () const
bool defaultsRead () const
void deleteItem (Element *)
void deleteLater (ScoreElement *e)
void deleteMeasures (MeasureBase *firstMeasure, MeasureBase *lastMeasure)
void deletePostponed ()
void deselect (Element *obj)
void deselectAll ()
bool dirty () const
void doLayout ()
void doLayoutRange (const Fraction &, const Fraction &)
Element * downAlt (Element *)
Note * downAltCtrl (Note *) const
void dragPosition (const QPointF &, int *staffIdx, Segment **) const
int duration ()
void endCmd (bool rollback=false)
Fraction endTick () const
Excerpt * excerpt ()
virtual QList< Excerpt * > & excerpts ()
virtual const QList< Excerpt * > & excerpts () const
void expandVoice ()
void expandVoice (Segment *s, int track)
QString extractLyrics ()
int fileDivision (int t) const
ChordRest * findCR (Fraction tick, int track) const
ChordRest * findCRinStaff (const Fraction &tick, int staffIdx) const
MeasureBase * first () const
Element * firstElement (bool frame=true)
Ms::Measure * firstMeasure () const
Ms::Measure * firstMeasureMM () const
MeasureBase * firstMM () const
Segment * firstSegment (SegmentType s) const
Segment * firstSegmentMM (SegmentType s) const
void fixTicks ()
bool floatMode () const
Text * footerText () const
void forAllLyrics (std::function< void(Lyrics *)> f)
bool genCourtesyClef () const
bool genCourtesyTimesig () const
Measure * getCreateMeasure (const Fraction &tick)
int getLinkId () const
void getNextMeasure (LayoutContext &)
System * getNextSystem (LayoutContext &)
bool getPosition (Position *pos, const QPointF &, int voice) const
virtual QVariant getProperty (Pid) const override
ChordRest * getSelectedChordRest () const
void getSelectedChordRest2 (ChordRest **cr1, ChordRest **cr2) const
QSet< ChordRest * > getSelectedChordRests () const
Element * getSelectedElement () const
Text * getText (Tid subtype)
QString getTextStyleUserName (Tid tid)
const QList< MuseScoreView * > & getViewer () const
void globalInsertChord (const Position &)
void globalTimeDelete ()
int harmonyCount ()
bool hasHarmonies ()
bool hasLyrics ()
Text * headerText () const
void hideEmptyStaves (System *system, bool isFirstSystem)
QString importedFilePath () const
Fraction inputPos () const
InputState & inputState ()
const InputState & inputState () const
int inputTrack () const
void insertChord (const Position &)
void insertMeasure (ElementType type, MeasureBase *, bool createEmptyMeasures=false, bool moveSignaturesClef=true)
void insertPart (Part *, int)
void insertStaff (Staff *, int)
void insertTime (const Fraction &tickPos, const Fraction &tickLen)
virtual bool isMaster () const
bool isPalette () const
bool isSpannerStartEnd (const Fraction &tick, int track) const
bool isTopScore () const
int keysig ()
void lassoSelect (const QRectF &)
void lassoSelectEnd ()
MeasureBase * last () const
Element * lastElement (bool frame=true)
Ms::Measure * lastMeasure () const
Ms::Measure * lastMeasureMM () const
Segment * lastSegment () const
Segment * lastSegmentMM () const
QList< Layer > & layer ()
const QList< Layer > & layer () const
QString * layerTagComments ()
QString * layerTags ()
void layoutChords1 (Segment *segment, int staffIdx)
qreal layoutChords2 (std::vector< Note * > &notes, bool up)
void layoutChords3 (std::vector< Note * > &, const Staff *, Segment *)
void layoutLinear (bool layoutAll, LayoutContext &lc)
void layoutLyrics (System *)
LayoutMode layoutMode () const
void layoutSystemElements (System *system, LayoutContext &lc)
bool lineMode () const
int linkId ()
void linkId (int)
bool loadStyle (const QString &, bool ign=false)
void localInsertChord (const Position &)
void localTimeDelete ()
qreal loHeight () const
Fraction loopInTick () const
Fraction loopOutTick () const
qreal loWidth () const
int lyricCount ()
Fraction makeGap (Segment *, int track, const Fraction &, Tuplet *, bool keepChord=false)
bool makeGap1 (const Fraction &baseTick, int staffIdx, const Fraction &len, int voiceOffset[VOICES])
bool makeGapVoice (Segment *seg, int track, Fraction len, const Fraction &tick)
bool markIrregularMeasures () const
MasterScore * masterScore () const
MeasureBase * measure (int idx) const
MeasureBaseList * measures ()
QString metaTag (const QString &tag) const
QMap< QString, QString > & metaTags ()
const QMap< QString, QString > & metaTags () const
virtual QQueue< MidiInputEvent > * midiInputQueue ()
Element * move (const QString &cmd)
void moveDown (ChordRest *)
void moveUp (ChordRest *)
int mscoreRevision () const
QString mscoreVersion () const
int mscVersion () const
Element * nextElement ()
void nextInputPos (ChordRest *cr, bool)
QString nextRehearsalMarkText (RehearsalMark *previous, RehearsalMark *current) const
Fraction nextSeg (const Fraction &tick, int track)
int nmeasures () const
bool noStaves () const
NoteEntryMethod noteEntryMethod () const
bool noteEntryMode () const
qreal noteHeadWidth () const
NoteVal noteValForPosition (Position pos, AccidentalType at, bool &error)
virtual int npages () const
int nstaves () const
int ntracks () const
Score & operator= (const Score &)=delete
virtual int pageIdx (Page *page) const
bool pageMode () const
int pageNumberOffset () const
virtual QList< Page * > & pages ()
virtual const QList< Page * > & pages () const
QList< Part * > & parts ()
const QList< Part * > & parts () const
bool pasteStaff (XmlReader &, Segment *dst, int staffIdx, Fraction scale=Fraction(1, 1))
void pasteSymbols (XmlReader &e, ChordRest *dst)
bool playChord () const
virtual bool playlistDirty () const
PlayMode playMode () const
bool playNote () const
Fraction playPos () const
qreal point (const Spatium sp) const
Fraction pos ()
Fraction pos (POS pos) const
Measure * pos2measure (const QPointF &, int *staffIdx, int *pitch, Segment **, QPointF *offset) const
Element * prevElement ()
void print (QPainter *printer, int page)
bool printing () const
bool processMidiInput ()
virtual QVariant propertyDefault (Pid) const override
void putNote (const QPointF &, bool replace, bool insert)
bool read (XmlReader &)
void readAddConnector (ConnectorInfoReader *info, bool pasteMode) override
virtual bool readOnly () const
void readStaff (XmlReader &)
void rebuildBspTree ()
void rebuildTempoAndTimeSigMaps (Measure *m)
void regroupNotesAndRests (const Fraction &startTick, const Fraction &endTick, int track)
void removeAudio ()
void removeElement (Element *)
void removePart (Part *)
void removeSpanner (Spanner *)
void removeStaff (Staff *)
void removeTempo (const Fraction &tick)
void removeUnmanagedSpanner (Spanner *)
void removeViewer (MuseScoreView *v)
void renderMidi (EventMap *events, bool metronome, bool expandRepeats, const SynthesizerState &synthState)
void renderMidi (EventMap *events, const SynthesizerState &synthState)
virtual const RepeatList & repeatList () const
void repitchNote (const Position &pos, bool replace)
void respace (std::vector< ChordRest * > *elements)
bool sanityCheck (const QString &name=QString())
bool saveCompressedFile (QFileInfo &, bool onlySelection, bool createThumbnail=true)
bool saveCompressedFile (QIODevice *, const QFileInfo &, bool onlySelection, bool createThumbnail=true)
bool saved () const
bool savedCapture () const
bool saveFile (QFileInfo &info)
bool saveFile (QIODevice *f, bool msczFormat, bool onlySelection=false)
bool saveStyle (const QString &)
void scanElements (void *data, void(*func)(void *, Element *), bool all=true)
void scanElementsInRange (void *data, void(*func)(void *, Element *), bool all=true)
ScoreFont * scoreFont () const
QList< Score * > scoreList ()
Measure * searchLabel (const QString &s, Measure *startMeasure=nullptr, Measure *endMeasure=nullptr)
Measure * searchLabelWithinSectionFirst (const QString &s, Measure *sectionStartMeasure, Measure *sectionEndMeasure)
Measure * searchMeasure (const QPointF &p) const
ChordRest * searchNote (const Fraction &tick, int track) const
Page * searchPage (const QPointF &) const
QList< System * > searchSystem (const QPointF &p) const
Tuplet * searchTuplet (XmlReader &e, int id)
void select (Element *obj, SelectType=SelectType::SINGLE, int staff=0)
Selection & selection ()
const Selection & selection () const
bool selectionChanged () const
SelectionFilter & selectionFilter ()
Element * selectMove (const QString &cmd)
void selectSimilar (Element *e, bool sameStaff)
void selectSimilarInRange (Element *e)
void setAccessibleInfo (QString s)
void setAudio (Audio *a)
void setAutosaveDirty (bool v)
Segment * setChord (Segment *, int track, Chord *chord, Fraction, Direction stemDirection=Direction::AUTO)
void setCreated (bool val)
void setCurrentLayer (int val)
void setDefaultsRead (bool b)
void setExcerpt (Excerpt *e)
void setFileDivision (int t)
void setFooterText (Text *t)
Note * setGraceNote (Chord *, int pitch, NoteType type, int len)
void setHeaderText (Text *t)
void setImportedFilePath (const QString &filePath)
void setInputState (const InputState &st)
void setInputTrack (int t)
virtual void setInstrumentsChanged (bool)
void setLayout (const Fraction &tick, int staff, const Element *e=nullptr)
void setLayout (const Fraction &tick1, const Fraction &tick2, int staff1, int staff2, const Element *e=nullptr)
void setLayoutAll (int staff=-1, const Element *e=nullptr)
void setLayoutMode (LayoutMode lm)
void setLoopInTick (const Fraction &tick)
void setLoopOutTick (const Fraction &tick)
void setMarkIrregularMeasures (bool v)
void setMasterScore (MasterScore *s)
void setMetaTag (const QString &tag, const QString &val)
void setMetaTags (const QMap< QString, QString > &t)
void setMscoreRevision (int val)
void setMscoreVersion (const QString &val)
void setMscVersion (int v)
void setNoteEntryMethod (NoteEntryMethod m)
void setNoteEntryMode (bool val)
void setNoteHeadWidth (qreal n)
Segment * setNoteRest (Segment *, int track, NoteVal nval, Fraction, Direction stemDirection=Direction::AUTO, bool forceAccidental=false, bool rhythmic=false)
void setPageNumberOffset (int v)
void setPaletteMode (bool palette)
void setPause (const Fraction &tick, qreal seconds)
void setPlayChord (bool v)
virtual void setPlaylistDirty ()
void setPlayMode (PlayMode v)
void setPlayNote (bool v)
void setPlayPos (const Fraction &tick)
void setPos (POS pos, Fraction tick)
void setPrinting (bool val)
virtual bool setProperty (Pid, const QVariant &) override
Rest * setRest (const Fraction &tick, int track, const Fraction &, bool useDots, Tuplet *tuplet, bool useFullMeasureRest=true)
void setSaved (bool v)
void setSavedCapture (bool v)
void setScoreFont (ScoreFont *f)
void setSelection (const Selection &s)
void setSelectionChanged (bool val)
void setShowFrames (bool v)
void setShowInstrumentNames (bool v)
void setShowInvisible (bool v)
void setShowPageborders (bool v)
void setShowUnprintable (bool v)
void setShowVBox (bool v)
void setSpatium (qreal v)
void setStyle (const MStyle &s)
void setStyleValue (Sid sid, QVariant value)
void setSynthesizerState (const SynthesizerState &s)
void setTempo (const Fraction &tick, qreal bps)
void setTempo (Segment *, qreal)
void setTmpName (const QString &s)
virtual void setUpdateAll ()
bool showFrames () const
bool showInstrumentNames () const
bool showInvisible () const
bool showPageborders () const
bool showUnprintable () const
bool showVBox () const
virtual TimeSigMap * sigmap () const
void sortStaves (QList< int > &dst)
const std::multimap< int, Spanner * > & spanner () const
SpannerMap & spannerMap ()
qreal spatium () const
void spatiumChanged (qreal oldValue, qreal newValue)
void spell ()
void spell (int startStaff, int endStaff, Segment *startSegment, Segment *endSegment)
void spell (Note *)
void spellNotelist (std::vector< Note * > &notes)
void splitMeasure (Segment *)
void splitStaff (int staffIdx, int splitPoint)
Staff * staff (int n) const
int staffIdx (const Part *) const
void startCmd ()
ScoreContentState state () const
QList< Staff * > & staves ()
const QList< Staff * > & staves () const
virtual MStyle & style ()
virtual const MStyle & style () const
bool styleB (Sid idx) const
void styleChanged ()
qreal styleD (Sid idx) const
int styleI (Sid idx) const
qreal styleP (Sid idx) const
Spatium styleS (Sid idx) const
QString styleSt (Sid idx) const
QVariant styleV (Sid idx) const
bool switchLayer (const QString &s)
void switchToPageMode ()
SynthesizerState & synthesizerState ()
bool systemMode () const
QList< System * > & systems ()
const QList< System * > & systems () const
bool tagIsValid (uint tag) const
qreal tempo (const Fraction &tick) const
virtual TempoMap * tempomap () const
BeatType tick2beatType (const Fraction &tick)
Segment * tick2leftSegment (const Fraction &tick, bool useMMrest=false) const
Measure * tick2measure (const Fraction &tick) const
MeasureBase * tick2measureBase (const Fraction &tick) const
Measure * tick2measureMM (const Fraction &tick) const
Segment * tick2rightSegment (const Fraction &tick, bool useMMrest=false) const
Segment * tick2segment (const Fraction &tick) const
Segment * tick2segment (const Fraction &tick, bool first) const
Segment * tick2segment (const Fraction &tick, bool first, SegmentType st, bool useMMrest=false) const
Segment * tick2segmentMM (const Fraction &tick) const
Segment * tick2segmentMM (const Fraction &tick, bool first) const
Segment * tick2segmentMM (const Fraction &tick, bool first, SegmentType st) const
void timeDelete (Measure *, Segment *, const Fraction &)
virtual QString title () const
QString tmpName () const
void toggleAccidental (AccidentalType, const EditData &ed)
bool transpose (Note *n, Interval, bool useSharpsFlats)
bool transpose (TransposeMode mode, TransposeDirection, Key transposeKey, int transposeInterval, bool trKeys, bool transposeChordNames, bool useDoubleSharpsFlats)
void transposeKeys (int staffStart, int staffEnd, const Fraction &tickStart, const Fraction &tickEnd, const Interval &, bool useInstrument=false, bool flip=false)
void transposeSemitone (int semitone)
void transpositionChanged (Part *, Interval, Fraction tickStart={ 0, 1 }, Fraction tickEnd={ -1, 1 })
virtual ElementType type () const override
void undo (UndoCommand *, EditData *=0) const
void undoAddBracket (Staff *staff, int level, BracketType type, int span)
void undoAddCR (ChordRest *element, Measure *, const Fraction &tick)
void undoAddElement (Element *element)
void undoChangeChordRestLen (ChordRest *cr, const TDuration &)
void undoChangeClef (Staff *ostaff, Element *, ClefType st, bool forInstrumentChange=false)
void undoChangeElement (Element *oldElement, Element *newElement)
void undoChangeFretting (Note *note, int pitch, int string, int fret, int tpc1, int tpc2)
void undoChangeInvisible (Element *, bool)
void undoChangeKeySig (Staff *ostaff, const Fraction &tick, KeySigEvent)
void undoChangePageNumberOffset (int po)
void undoChangePitch (Note *note, int pitch, int tpc1, int tpc2)
void undoChangeSpannerElements (Spanner *spanner, Element *startElement, Element *endElement)
void undoChangeStyleVal (Sid idx, const QVariant &v)
void undoChangeTpc (Note *note, int tpc)
void undoChangeTuning (Note *, qreal)
void undoChangeUserMirror (Note *, MScore::DirectionH)
void undoExchangeVoice (Measure *measure, int val1, int val2, int staff1, int staff2)
void undoInsertPart (Part *part, int idx)
void undoInsertStaff (Staff *staff, int idx, bool createRests=true)
void undoInsertTime (const Fraction &tick, const Fraction &len)
bool undoPropertyChanged (Element *e, Pid t, const QVariant &st, PropertyFlags ps=PropertyFlags::NOSTYLE)
void undoPropertyChanged (ScoreElement *, Pid, const QVariant &v, PropertyFlags ps=PropertyFlags::NOSTYLE)
void undoRedo (bool undo, EditData *)
void undoRemoveBracket (Bracket *)
void undoRemoveElement (Element *element)
void undoRemoveMeasures (Measure *, Measure *)
void undoRemovePart (Part *part, int idx)
void undoRemoveStaff (Staff *staff)
virtual UndoStack * undoStack () const
void undoTransposeHarmony (Harmony *, int, int)
QList< int > uniqueStaves () const
const std::set< Spanner * > unmanagedSpanners ()
Element * upAlt (Element *)
Note * upAltCtrl (Note *) const
void update ()
void updateCapo ()
void updateChannel ()
void updateHairpin (Hairpin *)
void updateInstrumentChangeTranspositions (Ms::KeySigEvent &key, Ms::Staff *staff, const Ms::Fraction &tick)
void updateSelection ()
void updateStaffIndex ()
void updateSwing ()
void updateVelo ()
void upDown (bool up, UpDownMode)
void upDownDelta (int pitchDelta)
bool usingNoteEntryMethod (NoteEntryMethod m)
qreal utick2utime (int tick) const
int utime2utick (qreal utime) const
void write (XmlWriter &, bool onlySelection)
void writeMovement (XmlWriter &, bool onlySelection)
void writeSegments (XmlWriter &xml, int strack, int etrack, Segment *sseg, Segment *eseg, bool, bool)
Public Functions inherited from Ms::ScoreElement
ScoreElement (const ScoreElement &se)
ScoreElement (Score *s)
virtual Sid getPropertyStyle (Pid) const
virtual void initElementStyle (const ElementStyle *)
bool isBox () const
bool isBSymbol () const
bool isChordRest () const
bool isDurationElement () const
virtual bool isElement () const
bool isLineSegment () const
bool isLinked (ScoreElement *)
bool isMeasureBase () const
bool isSLine () const
bool isSLineSegment () const
bool isSlurTieSegment () const
bool isSpanner () const
bool isSpannerSegment () const
bool isStaffTextBase () const
bool isStyled (Pid pid) const
bool isTextBase () const
bool isTextLineBase () const
bool isTextLineBaseSegment () const
bool isVBoxBase () const
int lid () const
QList< ScoreElement * > linkList () const
LinkedElements * links () const
void linkTo (ScoreElement *)
MasterScore * masterScore () const
const char * name () const
QVariant propertyDefault (Pid pid, Tid tid) const
virtual PropertyFlags propertyFlags (Pid) const
virtual PropertyFlags * propertyFlagsList () const
virtual Pid propertyId (const QStringRef &xmlName) const
virtual QString propertyUserValue (Pid) const
bool readProperty (const QStringRef &, XmlReader &, Pid)
void readProperty (XmlReader &, Pid)
bool readStyledProperty (XmlReader &e, const QStringRef &tag)
virtual void reset ()
virtual void resetProperty (Pid id)
Score * score () const
void setLinks (LinkedElements *le)
void setPropertyFlags (Pid, PropertyFlags)
virtual void setScore (Score *s)
virtual bool sizeIsSpatiumDependent () const
virtual const ElementStyle * styledProperties () const
QVariant styleValue (Pid, Sid) const
void undoChangeProperty (Pid id, const QVariant &)
virtual void undoChangeProperty (Pid id, const QVariant &, PropertyFlags ps)
void undoPushProperty (Pid)
void undoResetProperty (Pid id)
virtual void undoUnlink ()
void unlink ()
virtual QString userName () const
void writeProperty (XmlWriter &xml, Pid id) const
void writeStyledProperties (XmlWriter &) const
Signals
void playlistChanged ()
void posChanged (POS, unsigned)
Static Public Functions
static std::vector< Note * > cmdTieNoteList (const Selection &selection, bool noteEntryMode)
static void collectMatch (void *data, Element *e)
static void collectNoteMatch (void *data, Element *e)
constexpr static double defaultTempo ()
static void onElementDestruction (Element *se)
Static Public Functions inherited from Ms::ScoreElement
static const char * name (ElementType)
static ElementType name2type (const QString &s)
static ElementType name2type (const QStringRef &, bool silent=false)
Protected Functions
void cmdPadNoteDecreaseTAB (const EditData &ed)
void cmdPadNoteIncreaseTAB (const EditData &ed)
void cmdPitchDown ()
void cmdPitchDownOctave ()
void cmdPitchUp ()
void cmdPitchUpOctave ()
void cmdSetVisible ()
void cmdToggleHideEmpty ()
void cmdToggleMmrest ()
void cmdUnsetVisible ()
void createGraceNotesPlayEvents (const Fraction &tick, Chord *chord, int &ontime, int &trailtime)
void createPlayEvents (Chord *)
virtual Movements * movements ()
virtual const Movements * movements () const
Protected Functions inherited from Ms::ScoreElement
virtual int getPropertyFlagsIdx (Pid id) const
Protected Members
int _fileDivision
LayoutMode _layoutMode
SynthesizerState _synthesizerState
Protected Members inherited from Ms::ScoreElement
const ElementStyle * _elementStyle
LinkedElements * _links
PropertyFlags * _propertyFlagsList
Private Functions
void addAudioTrack ()
void addMetronome ()
void addTempo ()
void beamGraceNotes (Chord *, bool)
void checkScore ()
void checkSlurs ()
void cmdAddBracket ()
void cmdAddFret (int fret)
void cmdAddGrace (NoteType, int)
void cmdAddParentheses ()
void cmdAddPitch (const EditData &, int note, bool addFlag, bool insert)
void cmdFlip ()
void cmdIncDecDuration (int nSteps, bool stepDotted=false)
void cmdInsertClef (ClefType)
void cmdMoveLyrics (Lyrics *, Direction)
void cmdMoveRest (Rest *, Direction)
void cmdResetBeamMode ()
void cmdResetStyle ()
void cmdSetBeamMode (Beam::Mode)
void cmdToggleVisible ()
void collectLinearSystem (LayoutContext &lc)
void createMMRest (Measure *, Measure *, const Fraction &)
void deleteAnnotationsFromRange (Segment *segStart, Segment *segEnd, int trackStart, int trackEnd, const SelectionFilter &filter)
ChordRest * deleteRange (Segment *segStart, Segment *segEnd, int trackStart, int trackEnd, const SelectionFilter &filter)
void deleteSpannersFromRange (const Fraction &t1, const Fraction &t2, int trackStart, int trackEnd, const SelectionFilter &filter)
ChordRest * downStaff (ChordRest *cr)
Note * getSelectedNote ()
bool isSubdivided (ChordRest *, int)
ChordRest * nextMeasure (ChordRest *element, bool selectBehavior=false, bool mmRest=false)
ChordRest * nextTrack (ChordRest *cr)
void padToggle (Pad n, const EditData &ed)
void pasteChordRest (ChordRest *cr, const Fraction &tick, const Interval &)
ChordRest * prevMeasure (ChordRest *element, bool mmRest=false)
ChordRest * prevTrack (ChordRest *cr)
void putNote (const Position &, bool replace)
void removeChordRest (ChordRest *cr, bool clearSegment)
void resetSystems (bool layoutAll, LayoutContext &lc)
void resetTempo ()
void resetTempoRange (const Fraction &tick1, const Fraction &tick2)
void resetUserStretch ()
bool rewriteMeasures (Measure *fm, const Fraction &ns, int staffIdx)
bool rewriteMeasures (Measure *fm, Measure *lm, const Fraction &, int staffIdx)
void selectAdd (Element *e)
void selectRange (Element *e, int staffIdx)
void selectSingle (Element *e, int staffIdx)
QList< Fraction > splitGapToMeasureBoundaries (ChordRest *, Fraction)
void swingAdjustParams (Chord *, int &, int &, int, int)
void update (bool resetCmdState)
ChordRest * upStaff (ChordRest *cr)
Private Members
Audio * _audio
bool _autosaveDirty
bool _created
int _currentLayer
bool _defaultsRead
Excerpt * _excerpt
QString _importedFilePath
InputState _is
bool _isPalette
QList< Layer > _layer
QString _layerTagComments [32]
QString _layerTags [32]
int _linkId
bool _markIrregularMeasures
MasterScore * _masterScore
MeasureBaseList _measures
QMap< QString, QString > _metaTags
int _mscoreRevision
QString _mscoreVersion
int _mscVersion
qreal _noteHeadWidth
int _pageNumberOffset
QList< Page * > _pages
QList< Part * > _parts
PlayMode _playMode
bool _printing
bool _saved
bool _savedCapture
ScoreFont * _scoreFont
Selection _selection
SelectionFilter _selectionFilter
bool _showFrames
bool _showInstrumentNames
bool _showInvisible
bool _showPageborders
bool _showUnprintable
bool _showVBox
SpannerMap _spanner
QList< Staff * > _staves
MStyle _style
QList< System * > _systems
QString _tmpName
std::set< Spanner * > _unmanagedSpanner
UpdateState _updateState
QString accInfo
QList< MuseScoreView * > viewer
Private Static Members
constexpr static double _defaultTempo
static std::set< Score * > validScores
Friends
class ChangeSynthesizerState
class Chord
Member Function Documentation
addArticulation()
void Ms::Score::addArticulation (SymId attr)
Add attribute attr to all selected notes/rests.
Called from padToggle() to add note prefix/accent.
addElement()
void Ms::Score::addElement (Element * element)
Add element to its parent.
Several elements (clef, keysig, timesig) need special handling, as they may cause changes throughout the score.
References Ms::Part::updateHarmonyChannels().
changeAccidental() [1/2]
void Ms::Score::changeAccidental (AccidentalType idx)
Change accidental to subtype idx for all selected notes.
changeAccidental() [2/2]
void Ms::Score::changeAccidental (Note * note, Ms::AccidentalType accidental)
Change accidental to subtype \accidental for note note.
References Ms::Measure::findAccidental(), and Ms::NONE.
checkClefs()
bool Ms::Score::checkClefs ()
check that clef map is in sync with actual clefs
checkKeys()
bool Ms::Score::checkKeys ()
check that key map is in sync with actual keys
cmdAddFret()
void Ms::Score::cmdAddFret (int fret) private
insert note with given fret on current string
cmdAddGrace()
void Ms::Score::cmdAddGrace (NoteType graceType, int duration) private
adds grace note of specified type to selected notes
References setGraceNote().
cmdAddPitch()
void Ms::Score::cmdAddPitch (const EditData & ed, int note, bool addFlag, bool insert) private
insert note or add note to chord
References Ms::Note::epitch(), and Ms::Segment::prev1().
cmdExplode()
void Ms::Score::cmdExplode ()
explodes contents of top selected staff into subsequent staves
cmdImplode()
void Ms::Score::cmdImplode ()
implodes contents of selected staves into top staff for single staff, merge voices
References Ms::Segment::next1().
cmdRealizeChordSymbols()
void Ms::Score::cmdRealizeChordSymbols (bool literal = true, Voicing voicing = Voicing(-1), HDuration durationType = HDuration(-1))
Realize selected chord symbols into notes on the staff.
If a voicing and duration type are specified, the harmony voicing settings will be overridden by the passed parameters. Otherwise, the settings set on the harmony object will be used.
References Ms::RealizedHarmony::generateNotes(), Ms::RealizedHarmony::getActualDuration(), and Ms::RealizedHarmony::notes().
cmdResequenceRehearsalMarks()
void Ms::Score::cmdResequenceRehearsalMarks ()
resequences rehearsal marks within a range selection or, if nothing is selected, the entire score
References Ms::Segment::next1().
cmdSlashFill()
void Ms::Score::cmdSlashFill ()
fills selected region with slashes
References staffIdx().
cmdSlashRhythm()
void Ms::Score::cmdSlashRhythm ()
converts rhythms in selected region to slashes
References Ms::NORMAL.
connectTies()
void Ms::Score::connectTies (bool silent = false)
Rebuild tie connections.
References _mscVersion, and Ms::Segment::next1().
deleteAnnotationsFromRange()
void Ms::Score::deleteAnnotationsFromRange (Segment * s1, Segment * s2, int track1, int track2, const SelectionFilter & filter) private
Deletes annotations in the given range that match the given selection filter.
References Ms::Segment::next1().
Referenced by deleteRange().
deleteRange()
ChordRest * Ms::Score::deleteRange (Segment * s1, Segment * s2, int track1, int track2, const SelectionFilter & filter) private
Deletes elements in the given range that match the given selection filter.
Returns
A chord/rest inside the selected range that can be used to establish a selection after this deletion operation.
References deleteAnnotationsFromRange(), deleteSpannersFromRange(), and Ms::Segment::next1().
deleteSpannersFromRange()
void Ms::Score::deleteSpannersFromRange (const Fraction & t1, const Fraction & t2, int track1, int track2, const SelectionFilter & filter) private
Deletes spanners in the given range that match the given selection filter.
Referenced by deleteRange().
endCmd()
void Ms::Score::endCmd (bool rollback = false)
End a GUI command by (if undo) ending a user-visble undo and (always) updating the redraw area.
fixTicks()
void Ms::Score::fixTicks ()
This is needed after
inserting or removing a measure
changing the sigmap
after inserting/deleting time (changes the sigmap)
rebuildTempoAndTimeSigMaps()
void Ms::Score::rebuildTempoAndTimeSigMaps (Measure * m)
updates tempomap and time sig map for a measure
References Ms::Measure::add().
removeElement()
void Ms::Score::removeElement (Element * element)
Remove element from its parent. Several elements (clef, keysig, timesig) need special handling, as they may cause changes throughout the score.
References Ms::Part::updateHarmonyChannels().
sanityCheck()
bool Ms::Score::sanityCheck (const QString & name = QString())
Check that voice 1 is complete Check that voices > 1 contains less than measure duration
References staffIdx().
setGraceNote()
Note * Ms::Score::setGraceNote (Chord * ch, int pitch, NoteType type, int len)
Create a grace note in front of a normal note.
ch is the chord of the normal note
pitch is the pitch of the grace note
is the grace note type \len is the visual duration of the grace note (1/16 or 1/32)
References Ms::NORMAL.
Referenced by cmdAddGrace().
staffIdx()
int Ms::Score::staffIdx (const Part * part) const
Return index for the first staff of part.
Referenced by cmdSlashFill(), and sanityCheck().
startCmd()
void Ms::Score::startCmd ()
Start a GUI command by clearing the redraw area and starting a user-visible undo.
tick2leftSegment()
Segment * Ms::Score::tick2leftSegment (const Fraction & tick, bool useMMrest = false) const
return the segment at this tick position if any or the first segment before this tick position
tick2rightSegment()
Segment * Ms::Score::tick2rightSegment (const Fraction & tick, bool useMMrest = false) const
return the segment at this tick position if any or the first segment after this tick position
References Ms::Segment::next1().
upDown()
void Ms::Score::upDown (bool up, UpDownMode mode)
Increment/decrement pitch of note by one or by an octave.
Referenced by upDownDelta().
upDownDelta()
void Ms::Score::upDownDelta (int pitchDelta)
Add the delta to the pitch of note.
References upDown().
Member Data Documentation
_created
bool Ms::Score::_created private
file is never saved, has generated name
_defaultsRead
bool Ms::Score::_defaultsRead private
defaults were read at MusicXML import, allow export of defaults in convertermode
_fileDivision
int Ms::Score::_fileDivision protected
division of current loading *.msc file
_mscVersion
int Ms::Score::_mscVersion private
version of current loading *.msc file
Referenced by connectTies().
_pageNumberOffset
int Ms::Score::_pageNumberOffset private
Offset for page numbers.
_printing
bool Ms::Score::_printing private
True if we are drawing to a printer.
_saved
bool Ms::Score::_saved private
True if project was already saved; only on first save a backup file will be created, subsequent saves will not overwrite the backup file.
_savedCapture
bool Ms::Score::_savedCapture private
True if we saved an image capture.
_tmpName
QString Ms::Score::_tmpName private
auto saved with this name if not empty
accInfo
QString Ms::Score::accInfo private
information used by the screen-reader
Wed Apr 8 2020 15:30:38 by Doxygen 1.8.17