Ms::Segment Class Reference
Libmscore Home · All Classes · All Functions · All Variables
Ms::Segment Class Reference final
Inherits Ms::Element.
Public Functions
Segment (const Segment &)
Segment (Measure *, SegmentType, const Fraction &)
Segment (Measure *m=0)
virtual QString accessibleExtraInfo () const override
void add (Element *) override
const std::vector< Element * > & annotations () const
void clearAnnotations ()
Segment * clone () const override
ChordRest * cr (int track) const
void createShape (int staffIdx)
void createShapes ()
qreal dotPosX (int staffIdx) const
Element * element (int track) const
Ms::Element * elementAt (int track) const
std::vector< Element * > & elist ()
const std::vector< Element * > & elist () const
bool empty () const
Spatium extraLeadingSpace () const
Element * findAnnotation (ElementType type, int minTrack, int maxTrack)
std::vector< Element * > findAnnotations (ElementType type, int minTrack, int maxTrack)
Element * firstAnnotation (Segment *s, int activeStaff)
Element * firstElement (int staff)
Element * firstElementOfSegment (Segment *s, int activeStaff)
Element * firstInNextSegments (int activeStaff)
Spanner * firstSpanner (int activeStaff)
void fixStaffIdx ()
QVariant getProperty (Pid propertyId) const override
bool hasAnnotationOrElement (ElementType type, int minTrack, int maxTrack) const
bool hasElements () const
void insertStaff (int staff)
bool isAmbitusType () const
bool isBarLineType () const
bool isBeginBarLineType () const
bool isBreathType () const
bool isChordRestType () const
bool isClefType () const
bool isEndBarLineType () const
bool isHeaderClefType () const
bool isKeySigAnnounceType () const
bool isKeySigType () const
bool isStartRepeatBarLineType () const
bool isTimeSigAnnounceType () const
bool isTimeSigType () const
bool isType (const SegmentType t) const
Element * lastAnnotation (Segment *s, int activeStaff)
Element * lastElement (int staff)
Element * lastElementOfSegment (Segment *s, int activeStaff)
Element * lastInPrevSegments (int activeStaff)
Spanner * lastSpanner (int activeStaff)
Measure * measure () const
qreal minHorizontalCollidingDistance (Segment *ns) const
qreal minHorizontalDistance (Segment *, bool isSystemGap) const
qreal minLeft () const
qreal minLeft (const Shape &) const
qreal minRight () const
Segment * next () const
Segment * next (SegmentType) const
Segment * next1 () const
Segment * next1 (SegmentType) const
Segment * next1enabled () const
Segment * next1MM () const
Segment * next1MM (SegmentType) const
Segment * next1MMenabled () const
Segment * nextActive () const
Element * nextAnnotation (Element *e)
ChordRest * nextChordRest (int track, bool backwards=false) const
Segment * nextCR (int track=-1, bool sameStaff=false) const
virtual Element * nextElement ()
Element * nextElement (int activeStaff)
Element * nextElementOfSegment (Segment *s, Element *e, int activeStaff)
Segment * nextEnabled () const
bool notChordRestType (Segment *s)
bool operator< (const Segment &) const
bool operator> (const Segment &) const
Segment * prev () const
Segment * prev (SegmentType) const
Segment * prev1 () const
Segment * prev1 (SegmentType) const
Segment * prev1enabled () const
Segment * prev1MM () const
Segment * prev1MM (SegmentType) const
Segment * prev1MMenabled () const
Segment * prevActive () const
Element * prevAnnotation (Element *e)
virtual Element * prevElement ()
Element * prevElement (int activeStaff)
Element * prevElementOfSegment (Segment *s, Element *e, int activeStaff)
Segment * prevEnabled () const
QVariant propertyDefault (Pid) const override
void read (XmlReader &) override
void remove (Element *) override
void removeAnnotation (Element *e)
void removeElement (int track)
void removeStaff (int staff)
Fraction rtick () const override
void scanElements (void *data, void(*func)(void *, Element *), bool all=true) override
SegmentType segmentType () const
void setDotPosX (int staffIdx, qreal val)
void setElement (int track, Element *el)
void setExtraLeadingSpace (Spatium v)
void setNext (Segment *e)
void setPrev (Segment *e)
bool setProperty (Pid propertyId, const QVariant &) override
void setRtick (const Fraction &v)
void setScore (Score *) override
void setSegmentType (SegmentType t)
void setStretch (qreal v)
void setTicks (const Fraction &v)
void setWritten (bool val) const
void setX (qreal v)
std::vector< Shape > shapes ()
const std::vector< Shape > & shapes () const
void sortStaves (QList< int > &dst)
bool splitsTuplet () const
Shape & staffShape (int staffIdx)
const Shape & staffShape (int staffIdx) const
qreal stretch () const
const char * subTypeName () const
void swapElements (int i1, int i2)
System * system () const
Fraction tick () const override
Fraction ticks () const
ElementType type () const override
void write (XmlWriter &) const override
bool written () const
qreal x () const override
Public Functions inherited from Ms::Element
Element (const Element &)
Element (Score *=0, ElementFlags=ElementFlag::NOTHING)
virtual Q_INVOKABLE QString _name () const
QRectF abbox () const
virtual bool acceptDrop (EditData &) const
virtual QString accessibleInfo () const
virtual void addbbox (const QRectF &r) const
bool addToSkyline () const
bool autoplace () const
void autoplaceCalculateOffset (QRectF &r, qreal minDistance)
void autoplaceMeasureElement (bool above, bool add)
void autoplaceMeasureElement (bool add=true)
void autoplaceSegmentElement (bool above, bool add)
void autoplaceSegmentElement (bool add=true)
virtual qreal baseLine () const
virtual QRectF & bbox ()
virtual const QRectF & bbox () const
QRectF canvasBoundingRect () const
virtual QPointF canvasPos () const
qreal canvasX () const
virtual void change (Element *o, Element *n)
virtual QColor color () const
bool composition () const
bool concertPitch () const
bool contains (const QPointF &p) const
QColor curColor () const
QColor curColor (bool isVisible) const
QColor curColor (bool isVisible, QColor normalColor) const
bool custom (Pid) const
virtual Grip defaultGrip () const
void deleteLater ()
virtual QRectF drag (EditData &)
virtual QLineF dragAnchor () const
virtual void draw (QPainter *) const
void drawAt (QPainter *p, const QPointF &pt) const
virtual void drawEditMode (QPainter *, EditData &)
void drawSymbol (SymId id, QPainter *p, const QPointF &o, int n) const
void drawSymbol (SymId id, QPainter *p, const QPointF &o=QPointF(), qreal scale=1.0) const
void drawSymbols (const std::vector< SymId > &, QPainter *p, const QPointF &o, const QSizeF &scale) const
void drawSymbols (const std::vector< SymId > &, QPainter *p, const QPointF &o=QPointF(), qreal scale=1.0) const
virtual Element * drop (EditData &)
bool dropTarget () const
virtual void dump () const
virtual bool edit (EditData &)
virtual void editCopy (EditData &)
virtual void editCut (EditData &)
virtual void editDrag (EditData &)
bool enabled () const
virtual void endDrag (EditData &)
virtual void endEdit (EditData &)
virtual void endEditDrag (EditData &)
Measure * findMeasure ()
const Measure * findMeasure () const
MeasureBase * findMeasureBase ()
const MeasureBase * findMeasureBase () const
bool flag (ElementFlag f) const
bool generated () const
virtual QPointF gripAnchor (Grip) const
virtual int gripsCount () const
virtual std::vector< QPointF > gripsPositions (const EditData &) const
bool header () const
virtual qreal height () const
virtual Grip initialEditModeGrip () const
bool intersects (const QRectF &r) const
const QPointF & ipos () const
virtual bool isEditable () const
virtual bool isElement () const override
virtual bool isMovable () const
bool isNudged () const
bool isPrintable () const
virtual bool isUserModified () const
virtual void layout ()
virtual Element * linkedClone ()
virtual void localSpatiumChanged (qreal, qreal)
virtual qreal mag () const
qreal magS () const
virtual QByteArray mimeData (const QPointF &) const
Spatium minDistance () const
virtual bool mousePress (EditData &)
virtual void move (const QPointF &s)
virtual Element * nextElement ()
virtual bool nextGrip (EditData &) const
virtual Element * nextSegmentElement ()
virtual EditBehavior normalModeEditBehavior () const
const QPointF & offset () const
OffsetChange offsetChanged () const
Element & operator= (const Element &)=delete
QRectF pageBoundingRect () const
virtual QPointF pagePos () const
qreal pageX () const
Element * parent () const
Part * part () const
bool placeAbove () const
bool placeBelow () const
Placement placement () const
virtual bool placeMultiple () const
qreal point (const Spatium sp) const
virtual const QPointF pos () const
virtual Element * prevElement ()
virtual bool prevGrip (EditData &) const
virtual Element * prevSegmentElement ()
virtual Element * propertyDelegate (Pid)
virtual Pid propertyId (const QStringRef &xmlName) const override
virtual QString propertyUserValue (Pid) const override
virtual bool readProperties (XmlReader &)
bool rebaseMinDistance (qreal &md, qreal &yd, qreal sp, qreal rebase, bool above, bool fix)
qreal rebaseOffset (bool nox=true)
virtual void reset () override
QPointF & roffset ()
QPointF & rpos ()
qreal & rxoffset ()
qreal & rxpos ()
qreal & ryoffset ()
qreal & rypos ()
virtual QString screenReaderInfo () const
bool selectable () const
bool selected () const
virtual void setAutoplace (bool v)
virtual void setbbox (const QRectF &r) const
virtual void setColor (const QColor &c)
void setComposition (bool v) const
void setDropTarget (bool v) const
void setEnabled (bool val)
void setFlag (ElementFlag f, bool v)
void setFlag (ElementFlag f, bool v) const
void setGenerated (bool val)
void setHeader (bool v)
virtual void setHeight (qreal v)
void setMag (qreal val)
void setMinDistance (Spatium v)
virtual void setOffset (const QPointF &o)
void setOffset (qreal x, qreal y)
void setOffsetChanged (bool v, bool absolute=true, const QPointF &diff=QPointF())
void setParent (Element *e)
void setPlacement (Placement val)
void setPos (const QPointF &p)
void setPos (qreal x, qreal y)
void setSelectable (bool val)
virtual void setSelected (bool f)
void setSizeIsSpatiumDependent (bool v)
void setSystemFlag (bool v) const
void setTag (uint val)
virtual void setTrack (int val)
void setTrailer (bool val)
virtual void setVisible (bool f)
void setVoice (int v)
virtual void setWidth (qreal v)
void setZ (int val)
virtual Shape shape () const
virtual bool sizeIsSpatiumDependent () const override
qreal spatium () const
virtual void spatiumChanged (qreal, qreal)
Staff * staff () const
int staffIdx () const
StaffType * staffType () const
virtual void startDrag (EditData &)
virtual void startEdit (EditData &)
virtual void startEditDrag (EditData &)
qreal styleP (Sid idx) const
virtual int subtype () const
virtual Q_INVOKABLE QString subtypeName () const
qreal symAdvance (SymId id) const
QRectF symBbox (const std::vector< SymId > &) const
QRectF symBbox (SymId id) const
QPointF symCutOutNE (SymId id) const
QPointF symCutOutNW (SymId id) const
QPointF symCutOutSE (SymId id) const
QPointF symCutOutSW (SymId id) const
qreal symHeight (SymId id) const
bool symIsValid (SymId id) const
QPointF symStemDownNW (SymId id) const
QPointF symStemUpSE (SymId id) const
qreal symWidth (const std::vector< SymId > &) const
qreal symWidth (SymId id) const
bool systemFlag () const
uint tag () const
int track () const
bool trailer () const
virtual void triggerLayout () const
virtual void triggerLayoutAll () const
void undoChangeProperty (Pid id, const QVariant &)
virtual void undoChangeProperty (Pid id, const QVariant &, PropertyFlags ps)
virtual void undoChangeProperty (Pid id, const QVariant &, PropertyFlags ps) override
void undoSetColor (const QColor &c)
void undoSetVisible (bool v)
void updateGrips (EditData &) const
bool visible () const
int voice () const
virtual int vStaffIdx () const
virtual qreal width () const
virtual void writeProperties (XmlWriter &xml) const
virtual qreal y () const
int z () const
Public Functions inherited from Ms::ScoreElement
ScoreElement (const ScoreElement &se)
ScoreElement (Score *s)
virtual Sid getPropertyStyle (Pid) const
virtual void initElementStyle (const ElementStyle *)
bool isBox () const
bool isBSymbol () const
bool isChordRest () const
bool isDurationElement () const
bool isLineSegment () const
bool isLinked (ScoreElement *)
bool isMeasureBase () const
bool isSLine () const
bool isSLineSegment () const
bool isSlurTieSegment () const
bool isSpanner () const
bool isSpannerSegment () const
bool isStaffTextBase () const
bool isStyled (Pid pid) const
bool isTextBase () const
bool isTextLineBase () const
bool isTextLineBaseSegment () const
bool isVBoxBase () const
int lid () const
QList< ScoreElement * > linkList () const
LinkedElements * links () const
void linkTo (ScoreElement *)
MasterScore * masterScore () const
const char * name () const
QVariant propertyDefault (Pid pid, Tid tid) const
virtual PropertyFlags propertyFlags (Pid) const
virtual PropertyFlags * propertyFlagsList () const
virtual void readAddConnector (ConnectorInfoReader *info, bool pasteMode)
bool readProperty (const QStringRef &, XmlReader &, Pid)
void readProperty (XmlReader &, Pid)
bool readStyledProperty (XmlReader &e, const QStringRef &tag)
virtual void resetProperty (Pid id)
Score * score () const
void setLinks (LinkedElements *le)
void setPropertyFlags (Pid, PropertyFlags)
virtual void styleChanged ()
virtual const ElementStyle * styledProperties () const
QVariant styleValue (Pid, Sid) const
void undoChangeProperty (Pid id, const QVariant &)
void undoPushProperty (Pid)
void undoResetProperty (Pid id)
virtual void undoUnlink ()
void unlink ()
virtual QString userName () const
void writeProperty (XmlWriter &xml, Pid id) const
void writeStyledProperties (XmlWriter &) const
Static Public Functions
static SegmentType segmentType (ElementType type)
static const char * subTypeName (SegmentType)
Static Public Functions inherited from Ms::Element
static Ms::Element * create (Ms::ElementType type, Score *)
static Element * name2Element (const QStringRef &, Score *)
static Element * readMimeData (Score *score, const QByteArray &data, QPointF *, Fraction *)
static ElementType readType (XmlReader &node, QPointF *, Fraction *)
Static Public Functions inherited from Ms::ScoreElement
static const char * name (ElementType)
static ElementType name2type (const QString &s)
static ElementType name2type (const QStringRef &, bool silent=false)
Protected Functions
Element * getElement (int staff)
Protected Functions inherited from Ms::ScoreElement
virtual int getPropertyFlagsIdx (Pid id) const
Private Functions
void checkElement (Element *, int track)
void checkEmpty () const
void init ()
void setEmpty (bool val) const
Private Members
std::vector< Element * > _annotations
std::vector< qreal > _dotPosX
std::vector< Element * > _elist
Spatium _extraLeadingSpace
Segment * _next
Segment * _prev
SegmentType _segmentType
std::vector< Shape > _shapes
qreal _stretch
Fraction _tick
Fraction _ticks
Additional Inherited Members
Public Types inherited from Ms::Element
enum EditBehavior { SelectOnly, Edit }
Public Members inherited from Ms::Element
bool itemDiscovered
Protected Members inherited from Ms::Element
QColor _color
int _z
Protected Members inherited from Ms::ScoreElement
const ElementStyle * _elementStyle
LinkedElements * _links
PropertyFlags * _propertyFlagsList
Member Function Documentation
findAnnotation()
Element * Ms::Segment::findAnnotation (ElementType type, int minTrack, int maxTrack)
Returns the first found annotation of type type or nullptr if nothing was found.
Referenced by Ms::Harmony::findNext(), Ms::Harmony::findPrev(), and Ms::Harmony::ticksTilNext().
findAnnotations()
std::vector< Element * > Ms::Segment::findAnnotations (ElementType type, int minTrack, int maxTrack)
Returns the list of found annotations or nullptr if nothing was found.
hasAnnotationOrElement()
bool Ms::Segment::hasAnnotationOrElement (ElementType type, int minTrack, int maxTrack) const
return true if an annotation of type type or and element is found in the track range
hasElements()
bool Ms::Segment::hasElements () const
Returns true if the segment has at least one element. Annotations are not considered.
next1()
Segment * Ms::Segment::next1 () const
return next Segment, dont stop searching at end of Measure
Referenced by Ms::Score::cmdImplode(), Ms::Score::cmdResequenceRehearsalMarks(), Ms::Score::connectTies(), Ms::Score::deleteAnnotationsFromRange(), Ms::Score::deleteRange(), Ms::Harmony::findNext(), operator<(), Ms::Score::tick2rightSegment(), and Ms::Harmony::ticksTilNext().
operator<()
bool Ms::Segment::operator< (const Segment & s) const
return true if segment is before s in list
References next1().
operator>()
bool Ms::Segment::operator> (const Segment & s) const
return true if segment is after s in list
References prev1().
prev1()
Segment * Ms::Segment::prev1 () const
return previous Segment, dont stop searching at Measure begin
Referenced by Ms::Score::cmdAddPitch(), Ms::Harmony::findPrev(), and operator>().
Wed Apr 8 2020 15:30:38 by Doxygen 1.8.17