Ms::RealizedHarmony Class Reference
Libmscore Home · All Classes · All Functions · All Variables
Ms::RealizedHarmony Class Reference
#include "realizedharmony.h"
Public Types
using PitchMap = QMap< int, int >
using PitchMapIterator = QMapIterator< int, int >
Public Functions
RealizedHarmony (Harmony *h)
HDuration duration () const
const PitchMap generateNotes (int rootTpc, int bassTpc, bool literal, Voicing voicing, int transposeOffset) const
Fraction getActualDuration (HDuration durationType=HDuration::INVALID) const
Harmony * harmony ()
bool literal () const
const PitchMap & notes () const
const QList< int > pitches () const
void setDirty (bool dirty)
void setDuration (HDuration)
void setHarmony (Harmony *h)
void setLiteral (bool)
void setVoicing (Voicing)
const QList< int > tpcs () const
void update (int rootTpc, int bassTpc, int transposeOffset=0)
bool valid () const
Voicing voicing () const
Private Functions
void cascadeDirty (bool dirty)
PitchMap getIntervals (int rootTpc, bool literal=true) const
PitchMap normalizeNoteMap (const PitchMap &intervals, int rootTpc, int rootPitch, int max=128, bool enforceMaxAsGoal=false) const
Private Members
bool _dirty
HDuration _duration
Harmony * _harmony
bool _literal
PitchMap _notes
Voicing _voicing
Detailed Description
holds information and functions to assist in the realization of chord symbols. This is what is used to allow for chord symbol playback
Member Function Documentation
cascadeDirty()
void Ms::RealizedHarmony::cascadeDirty (bool dirty) private
cascades the dirty flag backwards so that everything is properly set this is required since voicing algorithms may look ahead
NOTE: FOR NOW ALGORITHMS DO NOT LOOK BACKWARDS AND SO THERE IS NO REQUIREMENT TO CASCADE FORWARD, IN THE FUTURE IT MAY BECOME IMPORTANT TO CASCADE FORWARD AS WELL
References cascadeDirty(), and Ms::Harmony::findPrev().
Referenced by cascadeDirty(), setDuration(), setLiteral(), and setVoicing().
generateNotes()
const RealizedHarmony::PitchMap Ms::RealizedHarmony::generateNotes (int rootTpc, int bassTpc, bool literal, Voicing voicing, int transposeOffset) const
generates a note list based on the passed parameters
References notes().
Referenced by Ms::Score::cmdRealizeChordSymbols().
getActualDuration()
Fraction Ms::RealizedHarmony::getActualDuration (HDuration durationType = HDuration::INVALID) const
gets the fraction duration for how long the harmony should be realized based on the HDuration set.
This is opposed to RealizedHarmony::duration() which returns the HDuration, which is the duration setting.
Specifying a parameter finds a duration based on the passed duration type while not specifying a parameter uses the setting set by the user for the specific harmony object.
Referenced by Ms::Score::cmdRealizeChordSymbols().
getIntervals()
RealizedHarmony::PitchMap Ms::RealizedHarmony::getIntervals (int rootTpc, bool literal = true) const private
gets a weighted map from intervals to TPCs based on a passed root tpc (this allows for us to keep pitches, but transpose notes on the score)
Weighting System:
Rank 0: 3rd, altered 5th, suspensions (characteristic notes)
Rank 1: 7th
Rank 2: 9ths
Rank 3: 13ths where applicable and (in minor chords) 11ths
Rank 3: Other alterations and additions
Rank 4: 5th and (in major/dominant chords) 11th
References Ms::Harmony::findNext(), Ms::step2pitchInterval(), and Ms::tpcInterval().
normalizeNoteMap()
RealizedHarmony::PitchMap Ms::RealizedHarmony::normalizeNoteMap (const PitchMap & intervals, int rootTpc, int rootPitch, int max = 128, bool enforceMaxAsGoal = false) const private
normalize the pitch map from intervals to create pitches between 0 and 12 and resolve any weighting system.
enforceMaxEquals - enforce the max as a goal so that the max is how many notes is inserted
notes()
const RealizedHarmony::PitchMap & Ms::RealizedHarmony::notes () const
returns the list of notes
Referenced by Ms::Score::cmdRealizeChordSymbols(), and generateNotes().
setDuration()
void Ms::RealizedHarmony::setDuration (HDuration d)
sets the duration and dirty flag if the passed HDuration is different than current
References cascadeDirty().
setLiteral()
void Ms::RealizedHarmony::setLiteral (bool literal)
sets literal/jazz and dirty flag if the passed bool is different than current
References cascadeDirty().
setVoicing()
void Ms::RealizedHarmony::setVoicing (Voicing v)
sets the voicing and dirty flag if the passed voicing is different than current
References cascadeDirty().
update()
void Ms::RealizedHarmony::update (int rootTpc, int bassTpc, int transposeOffset = 0)
updates the current note map, this is where all of the rhythm and voicing choices matter since the voicing algorithms depend on this.
transposeOffset – is the necessary adjustment that is added to the root and bass to get the correct sounding pitch
TODO -: Don't worry about realized harmony for RNA harmony?
Wed Apr 8 2020 15:30:38 by Doxygen 1.8.17