Ms::Measure Class Reference
Libmscore Home · All Classes · All Functions · All Variables
Ms::Measure Class Reference final
#include "measure.h"
Inherits Ms::MeasureBase.
Public Functions
Measure (const Measure &)
Measure (Score *=0)
bool acceptDrop (EditData &) const override
QString accessibleInfo () const override
void add (Element *) override
void addSystemHeader (bool firstSystem)
void addSystemTrailer (Measure *nm)
void adjustToLen (Fraction, bool appendRestsIfNecessary=true)
void barLinesSetSpan (Segment *)
qreal basicStretch () const
qreal basicWidth () const
bool breakMultiMeasureRest () const
void change (Element *o, Element *n) override
void checkHeader ()
void checkMeasure (int idx)
void checkMultiVoices (int staffIdx)
void checkTrailer ()
Measure * clone () const override
Measure * cloneMeasure (Score *, const Fraction &tick, TieMap *)
void cmdAddStaves (int s, int e, bool createRest)
RepeatMeasure * cmdInsertRepeatMeasure (int staffIdx)
void cmdRemoveStaves (int s, int e)
void computeMinWidth ()
Fraction computeTicks ()
void connectTremolo ()
bool corrupted (int staffIdx) const
qreal createEndBarLines (bool)
void createStaves (int)
void createVoice (int track)
Element * drop (EditData &) override
bool empty () const
const BarLine * endBarLine () const
BarLineType endBarLineType () const
bool endBarLineVisible () const
void exchangeVoice (int voice1, int voice2, int staffIdx)
AccidentalVal findAccidental (Note *) const
AccidentalVal findAccidental (Segment *s, int staffIdx, int line, bool &error) const
Chord * findChord (Fraction tick, int track)
ChordRest * findChordRest (Fraction tick, int track)
Segment * findFirstR (SegmentType st, const Fraction &rtick) const
Segment * findSegment (SegmentType st, const Fraction &f) const
Segment * findSegmentR (SegmentType st, const Fraction &) const
Ms::Segment * first () const
Segment * first (SegmentType t) const
Segment * firstEnabled () const
QVariant getProperty (Pid propertyId) const override
Segment * getSegment (SegmentType st, const Fraction &f)
Segment * getSegmentR (SegmentType st, const Fraction &f)
bool hasMMRest () const
bool hasVoice (int track) const
bool hasVoices (int staffIdx) const
void insertMStaff (MStaff *staff, int idx)
void insertStaff (Staff *, int staff)
void insertStaves (int s, int e)
bool isAnacrusis () const
bool isEditable () const override
bool isEmpty (int staffIdx) const
bool isFinalMeasureOfSection () const
bool isFirstInSystem () const
bool isFullMeasureRest () const
bool isIrregular () const
bool isMMRest () const
bool isOnlyDeletedRests (int track) const
bool isOnlyDeletedRests (int track, const Fraction &stick, const Fraction &etick) const
bool isOnlyRests (int track) const
bool isRepeatMeasure (const Staff *staff) const
Ms::Segment * last () const
void layout2 ()
void layoutMeasureNumber ()
void layoutStaffLines ()
int layoutWeight (int maxMMRestLength=0) const
MeasureNumberMode measureNumberMode () const
Measure * mmRest () const
const Measure * mmRest1 () const
int mmRestCount () const
Measure * mmRestFirst () const
Measure * mmRestLast () const
void moveTicks (const Fraction &diff) override
Element * nextElementStaff (int staff)
MeasureNumber * noText (int staffIdx) const
int playbackCount () const
Element * prevElementStaff (int staff)
QVariant propertyDefault (Pid) const override
void read (XmlReader &, int idx)
void read (XmlReader &d)
void readAddConnector (ConnectorInfoReader *info, bool pasteMode) override
void readBox (XmlReader &)
void remove (Element *) override
void removeMStaff (MStaff *staff, int idx)
void removeStaves (int s, int e)
void removeSystemHeader ()
void removeSystemTrailer ()
int repeatCount () const
void scanElements (void *data, void(*func)(void *, Element *), bool all=true) override
SegmentList & segments ()
const SegmentList & segments () const
void setBreakMultiMeasureRest (bool val)
void setCorrupted (int staffIdx, bool val)
void setEndBarLineType (BarLineType val, int track, bool visible=true, QColor color=QColor())
void setHasVoices (int staffIdx, bool v)
void setMeasureNumberMode (MeasureNumberMode v)
void setMMRest (Measure *m)
void setMMRestCount (int n)
void setNoText (int staffIdx, MeasureNumber *)
void setPlaybackCount (int val)
bool setProperty (Pid propertyId, const QVariant &) override
void setRepeatCount (int val)
void setScore (Score *s) override
void setStaffStemless (int staffIdx, bool stemless)
void setStaffVisible (int staffIdx, bool visible)
void setStretchedWidth (qreal)
void setTimesig (const Fraction &f)
void setUserStretch (qreal v)
int size () const
Fraction snap (const Fraction &tick, const QPointF p) const
Fraction snapNote (const Fraction &tick, const QPointF p, int staff) const
void sortStaves (QList< int > &dst)
void spatiumChanged (qreal oldValue, qreal newValue) override
QRectF staffabbox (int staffIdx) const
StaffLines * staffLines (int staffIdx)
bool stemless (int staffIdx) const
Fraction stretchedLen (Staff *) const
void stretchMeasure (qreal stretch)
System * system () const
qreal tick2pos (Fraction) const
Segment * tick2segment (const Fraction &tick, SegmentType st=SegmentType::ChordRest)
Fraction timesig () const
void triggerLayout () const override
ElementType type () const override
Segment * undoGetSegment (SegmentType st, const Fraction &f)
Segment * undoGetSegmentR (SegmentType st, const Fraction &f)
qreal userStretch () const
bool visible (int staffIdx) const
Spacer * vspacerDown (int staffIdx) const
Spacer * vspacerUp (int staffIdx) const
void write (XmlWriter &, int, bool writeSystemElements, bool forceTimeSig) const
void write (XmlWriter &xml) const override
void writeBox (XmlWriter &) const
Public Functions inherited from Ms::MeasureBase
MeasureBase (const MeasureBase &)
MeasureBase (Score *score=0)
void clearElements ()
ElementList & el ()
const ElementList & el () const
Fraction endTick () const
bool hasCourtesyKeySig () const
int index () const
bool irregular () const
virtual void layout ()
bool lineBreak () const
int measureIndex () const
MeasureBase * next () const
Ms::Measure * nextMeasure () const
Ms::Measure * nextMeasureMM () const
MeasureBase * nextMM () const
int no () const
bool noBreak () const
int noOffset () const
bool pageBreak () const
qreal pause () const
MeasureBase * prev () const
Ms::Measure * prevMeasure () const
Ms::Measure * prevMeasureMM () const
MeasureBase * prevMM () const
virtual bool readProperties (XmlReader &) override
bool repeatEnd () const
bool repeatJump () const
bool repeatStart () const
bool sectionBreak () const
LayoutBreak * sectionBreakElement () const
void setHasCourtesyKeySig (int v)
void setIrregular (bool v)
void setLineBreak (bool v)
void setNext (MeasureBase *e)
void setNo (int n)
void setNoBreak (bool v)
void setNoOffset (int n)
void setPageBreak (bool v)
void setPrev (MeasureBase *e)
void setRepeatEnd (bool v)
void setRepeatJump (bool v)
void setRepeatStart (bool v)
void setSectionBreak (bool v)
void setSystem (System *s)
void setTick (const Fraction &f)
void setTicks (const Fraction &f)
System * system () const
ElementList takeElements ()
Fraction tick () const
Fraction ticks () const
void triggerLayout () const override
void undoSetBreak (bool v, LayoutBreak::Type type)
void undoSetLineBreak (bool v)
void undoSetNoBreak (bool v)
void undoSetPageBreak (bool v)
void undoSetSectionBreak (bool v)
virtual void writeProperties (XmlWriter &) const override
Public Functions inherited from Ms::Element
Element (const Element &)
Element (Score *=0, ElementFlags=ElementFlag::NOTHING)
virtual Q_INVOKABLE QString _name () const
QRectF abbox () const
virtual QString accessibleExtraInfo () const
virtual void addbbox (const QRectF &r) const
bool addToSkyline () const
bool autoplace () const
void autoplaceCalculateOffset (QRectF &r, qreal minDistance)
void autoplaceMeasureElement (bool above, bool add)
void autoplaceMeasureElement (bool add=true)
void autoplaceSegmentElement (bool above, bool add)
void autoplaceSegmentElement (bool add=true)
virtual qreal baseLine () const
virtual QRectF & bbox ()
virtual const QRectF & bbox () const
QRectF canvasBoundingRect () const
virtual QPointF canvasPos () const
qreal canvasX () const
virtual QColor color () const
bool composition () const
bool concertPitch () const
bool contains (const QPointF &p) const
QColor curColor () const
QColor curColor (bool isVisible) const
QColor curColor (bool isVisible, QColor normalColor) const
bool custom (Pid) const
virtual Grip defaultGrip () const
void deleteLater ()
virtual QRectF drag (EditData &)
virtual QLineF dragAnchor () const
virtual void draw (QPainter *) const
void drawAt (QPainter *p, const QPointF &pt) const
virtual void drawEditMode (QPainter *, EditData &)
void drawSymbol (SymId id, QPainter *p, const QPointF &o, int n) const
void drawSymbol (SymId id, QPainter *p, const QPointF &o=QPointF(), qreal scale=1.0) const
void drawSymbols (const std::vector< SymId > &, QPainter *p, const QPointF &o, const QSizeF &scale) const
void drawSymbols (const std::vector< SymId > &, QPainter *p, const QPointF &o=QPointF(), qreal scale=1.0) const
bool dropTarget () const
virtual void dump () const
virtual bool edit (EditData &)
virtual void editCopy (EditData &)
virtual void editCut (EditData &)
virtual void editDrag (EditData &)
bool enabled () const
virtual void endDrag (EditData &)
virtual void endEdit (EditData &)
virtual void endEditDrag (EditData &)
Measure * findMeasure ()
const Measure * findMeasure () const
MeasureBase * findMeasureBase ()
const MeasureBase * findMeasureBase () const
bool flag (ElementFlag f) const
bool generated () const
virtual QPointF gripAnchor (Grip) const
virtual int gripsCount () const
virtual std::vector< QPointF > gripsPositions (const EditData &) const
bool header () const
virtual qreal height () const
virtual Grip initialEditModeGrip () const
bool intersects (const QRectF &r) const
const QPointF & ipos () const
virtual bool isElement () const override
virtual bool isMovable () const
bool isNudged () const
bool isPrintable () const
virtual bool isUserModified () const
virtual Element * linkedClone ()
virtual void localSpatiumChanged (qreal, qreal)
virtual qreal mag () const
qreal magS () const
virtual QByteArray mimeData (const QPointF &) const
Spatium minDistance () const
virtual bool mousePress (EditData &)
virtual void move (const QPointF &s)
virtual Element * nextElement ()
virtual bool nextGrip (EditData &) const
virtual Element * nextSegmentElement ()
virtual EditBehavior normalModeEditBehavior () const
const QPointF & offset () const
OffsetChange offsetChanged () const
Element & operator= (const Element &)=delete
QRectF pageBoundingRect () const
virtual QPointF pagePos () const
qreal pageX () const
Element * parent () const
Part * part () const
bool placeAbove () const
bool placeBelow () const
Placement placement () const
virtual bool placeMultiple () const
qreal point (const Spatium sp) const
virtual const QPointF pos () const
virtual Element * prevElement ()
virtual bool prevGrip (EditData &) const
virtual Element * prevSegmentElement ()
virtual Element * propertyDelegate (Pid)
virtual Pid propertyId (const QStringRef &xmlName) const override
virtual QString propertyUserValue (Pid) const override
bool rebaseMinDistance (qreal &md, qreal &yd, qreal sp, qreal rebase, bool above, bool fix)
qreal rebaseOffset (bool nox=true)
virtual void reset () override
QPointF & roffset ()
QPointF & rpos ()
virtual Fraction rtick () const
qreal & rxoffset ()
qreal & rxpos ()
qreal & ryoffset ()
qreal & rypos ()
virtual QString screenReaderInfo () const
bool selectable () const
bool selected () const
virtual void setAutoplace (bool v)
virtual void setbbox (const QRectF &r) const
virtual void setColor (const QColor &c)
void setComposition (bool v) const
void setDropTarget (bool v) const
void setEnabled (bool val)
void setFlag (ElementFlag f, bool v)
void setFlag (ElementFlag f, bool v) const
void setGenerated (bool val)
void setHeader (bool v)
virtual void setHeight (qreal v)
void setMag (qreal val)
void setMinDistance (Spatium v)
virtual void setOffset (const QPointF &o)
void setOffset (qreal x, qreal y)
void setOffsetChanged (bool v, bool absolute=true, const QPointF &diff=QPointF())
void setParent (Element *e)
void setPlacement (Placement val)
void setPos (const QPointF &p)
void setPos (qreal x, qreal y)
void setSelectable (bool val)
virtual void setSelected (bool f)
void setSizeIsSpatiumDependent (bool v)
void setSystemFlag (bool v) const
void setTag (uint val)
virtual void setTrack (int val)
void setTrailer (bool val)
virtual void setVisible (bool f)
void setVoice (int v)
virtual void setWidth (qreal v)
void setZ (int val)
virtual Shape shape () const
virtual bool sizeIsSpatiumDependent () const override
qreal spatium () const
Staff * staff () const
int staffIdx () const
StaffType * staffType () const
virtual void startDrag (EditData &)
virtual void startEdit (EditData &)
virtual void startEditDrag (EditData &)
qreal styleP (Sid idx) const
virtual int subtype () const
virtual Q_INVOKABLE QString subtypeName () const
qreal symAdvance (SymId id) const
QRectF symBbox (const std::vector< SymId > &) const
QRectF symBbox (SymId id) const
QPointF symCutOutNE (SymId id) const
QPointF symCutOutNW (SymId id) const
QPointF symCutOutSE (SymId id) const
QPointF symCutOutSW (SymId id) const
qreal symHeight (SymId id) const
bool symIsValid (SymId id) const
QPointF symStemDownNW (SymId id) const
QPointF symStemUpSE (SymId id) const
qreal symWidth (const std::vector< SymId > &) const
qreal symWidth (SymId id) const
bool systemFlag () const
uint tag () const
int track () const
bool trailer () const
virtual void triggerLayoutAll () const
void undoChangeProperty (Pid id, const QVariant &)
virtual void undoChangeProperty (Pid id, const QVariant &, PropertyFlags ps)
virtual void undoChangeProperty (Pid id, const QVariant &, PropertyFlags ps) override
void undoSetColor (const QColor &c)
void undoSetVisible (bool v)
void updateGrips (EditData &) const
bool visible () const
int voice () const
virtual int vStaffIdx () const
virtual qreal width () const
virtual qreal x () const
virtual qreal y () const
int z () const
Public Functions inherited from Ms::ScoreElement
ScoreElement (const ScoreElement &se)
ScoreElement (Score *s)
virtual Sid getPropertyStyle (Pid) const
virtual void initElementStyle (const ElementStyle *)
bool isBox () const
bool isBSymbol () const
bool isChordRest () const
bool isDurationElement () const
bool isLineSegment () const
bool isLinked (ScoreElement *)
bool isMeasureBase () const
bool isSLine () const
bool isSLineSegment () const
bool isSlurTieSegment () const
bool isSpanner () const
bool isSpannerSegment () const
bool isStaffTextBase () const
bool isStyled (Pid pid) const
bool isTextBase () const
bool isTextLineBase () const
bool isTextLineBaseSegment () const
bool isVBoxBase () const
int lid () const
QList< ScoreElement * > linkList () const
LinkedElements * links () const
void linkTo (ScoreElement *)
MasterScore * masterScore () const
const char * name () const
QVariant propertyDefault (Pid pid, Tid tid) const
virtual PropertyFlags propertyFlags (Pid) const
virtual PropertyFlags * propertyFlagsList () const
bool readProperty (const QStringRef &, XmlReader &, Pid)
void readProperty (XmlReader &, Pid)
bool readStyledProperty (XmlReader &e, const QStringRef &tag)
virtual void resetProperty (Pid id)
Score * score () const
void setLinks (LinkedElements *le)
void setPropertyFlags (Pid, PropertyFlags)
virtual void styleChanged ()
virtual const ElementStyle * styledProperties () const
QVariant styleValue (Pid, Sid) const
void undoChangeProperty (Pid id, const QVariant &)
void undoPushProperty (Pid)
void undoResetProperty (Pid id)
virtual void undoUnlink ()
void unlink ()
virtual QString userName () const
void writeProperty (XmlWriter &xml, Pid id) const
void writeStyledProperties (XmlWriter &) const
Private Functions
void computeMinWidth (Segment *s, qreal x, bool isSystemHeader)
void fillGap (const Fraction &pos, const Fraction &len, int track, const Fraction &stretch)
void push_back (Segment *e)
void push_front (Segment *e)
void readVoice (XmlReader &e, int staffIdx, bool irregular)
Private Members
bool _breakMultiMeasureRest
Measure * _mmRest
int _mmRestCount
std::vector< MStaff * > _mstaves
MeasureNumberMode _noMode
int _playbackCount
int _repeatCount
SegmentList _segments
Fraction _timesig
qreal _userStretch
Additional Inherited Members
Public Types inherited from Ms::Element
enum EditBehavior { SelectOnly, Edit }
Public Members inherited from Ms::Element
bool itemDiscovered
Static Public Functions inherited from Ms::Element
static Ms::Element * create (Ms::ElementType type, Score *)
static Element * name2Element (const QStringRef &, Score *)
static Element * readMimeData (Score *score, const QByteArray &data, QPointF *, Fraction *)
static ElementType readType (XmlReader &node, QPointF *, Fraction *)
Static Public Functions inherited from Ms::ScoreElement
static const char * name (ElementType)
static ElementType name2type (const QString &s)
static ElementType name2type (const QStringRef &, bool silent=false)
Protected Functions inherited from Ms::MeasureBase
void cleanupLayoutBreaks (bool undo)
Protected Functions inherited from Ms::ScoreElement
virtual int getPropertyFlagsIdx (Pid id) const
Protected Members inherited from Ms::MeasureBase
Fraction _len
Protected Members inherited from Ms::Element
QColor _color
int _z
Protected Members inherited from Ms::ScoreElement
const ElementStyle * _elementStyle
LinkedElements * _links
PropertyFlags * _propertyFlagsList
Detailed Description
one measure in a system
Member Function Documentation
acceptDrop()
bool Ms::Measure::acceptDrop (EditData & data) const override virtual
Return true if an Element of type type can be dropped on a Measure
Reimplemented from Ms::Element.
References Ms::Element::canvasPos().
add()
void Ms::Measure::add (Element * e) override virtual
Add new Element el to Measure.
Reimplemented from Ms::MeasureBase.
Referenced by getSegmentR(), and Ms::Score::rebuildTempoAndTimeSigMaps().
addSystemHeader()
void Ms::Measure::addSystemHeader (bool isFirstSystem)
Add elements to make this measure suitable as the first measure of a system.
checkMultiVoices()
void Ms::Measure::checkMultiVoices (int staffIdx)
Check for more than on voice in this measure and staff and set MStaff->hasVoices
connectTremolo()
void Ms::Measure::connectTremolo ()
Connect two-notes tremolo and update duration types for the involved chords.
drop()
Element * Ms::Measure::drop (EditData & data) override virtual
Drop element. Handle a dropped element at position pos of given element type and subtype.
Reimplemented from Ms::Element.
findAccidental() [1/2]
AccidentalVal Ms::Measure::findAccidental (Note * note) const
return current accidental value at note position
References Ms::absStep().
Referenced by Ms::Score::changeAccidental().
findAccidental() [2/2]
AccidentalVal Ms::Measure::findAccidental (Segment * s, int staffIdx, int line, bool & error) const
Compute accidental state at segment/staffIdx for relative staff line.
References Ms::absStep(), and Ms::relStep().
findChord()
Chord * Ms::Measure::findChord (Fraction tick, int track)
Search for chord at position tick in track.
findChordRest()
ChordRest * Ms::Measure::findChordRest (Fraction tick, int track)
Search for chord or rest at position tick at staff in voice.
getSegmentR()
Segment * Ms::Measure::getSegmentR (SegmentType st, const Fraction & t)
Get a segment of type st at relative tick position t. If the segment does not exist, it is created.
References add().
isEmpty()
bool Ms::Measure::isEmpty (int staffIdx) const
Check if the measure is filled by a full-measure rest, or is full of rests on this staff, that may have fermatas on them. If staff is -1, then check for all staves.
remove()
void Ms::Measure::remove (Element * e) override virtual
Remove Element el from Measure.
Reimplemented from Ms::MeasureBase.
Member Data Documentation
_repeatCount
int Ms::Measure::_repeatCount private
end repeat marker und repeat count
Wed Apr 8 2020 15:30:37 by Doxygen 1.8.17